AWSTemplateFormatVersion: '2010-09-09'
Description: 'Phase 3 Minimal Infrastructure - Essential Document Storage'

Resources:
  # Essential Documents Table
  DocumentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 'Documents'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: document_id
          AttributeType: S
        - AttributeName: lead_id
          AttributeType: S
        - AttributeName: uploaded_at
          AttributeType: S
      KeySchema:
        - AttributeName: document_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: LeadDocumentsIndex
          KeySchema:
            - AttributeName: lead_id
              KeyType: HASH
            - AttributeName: uploaded_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # Essential Document Activity Table
  DocumentActivityTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 'DocumentActivity'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: activity_id
          AttributeType: S
        - AttributeName: document_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: activity_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: DocumentActivityIndex
          KeySchema:
            - AttributeName: document_id
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # Essential S3 Bucket
  DocumentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  DocumentsTableName:
    Description: 'Documents table name'
    Value: !Ref DocumentsTable
  
  DocumentActivityTableName:
    Description: 'Document activity table name'
    Value: !Ref DocumentActivityTable
  
  DocumentsBucketName:
    Description: 'Documents bucket name'
    Value: !Ref DocumentsBucket 